cds-snc/forms-api

Dockerfile
README.md
index.js

Update the API to run on port 3001 by default.  This will prevent local port clashes with the form viewer's default port.

chore: use port 3001 by default

---

Dockerfile

Upgrade the API Docker image to use Node 22.5.1 and pin to the image SHA.
- https://github.com/cds-snc/platform-forms-client/issues/3946

fix: upgrade to Node 22

---

.github/workflows/staging-deploy.yml

Upgrade to the latest versions of the GitHub actions to remove deprecation warnings from the workflow logs.
- https://github.com/cds-snc/platform-forms-client/issues/4128

chore: upgrade ECS task and deploy actions

---

.github/workflows/staging-deploy.yml

Linked to https://github.com/cds-snc/forms-terraform/pull/766
- Renames ECS Task name from `form-api` to `forms-api`

chore: rename ECS API task from form-api to forms-api

---

.github/workflows/staging-deploy.yml

Update the workflow to trigger a new deploy of the latest ACTIVE task definition using the AWS CLI.
This is being done so that the ECS service's task definition attribute remains in sync with the Terraform.
The behaviour of the ECS service has been updated to always deploy the latest ACTIVE task definition, thereby giving precedence to the deployment workflows in this repo.
- https://github.com/cds-snc/forms-terraform/pull/767
- https://github.com/cds-snc/platform-forms-client/issues/4128
- https://github.com/cds-snc/terraform-modules/pull/544

fix: deploy latest task definition

---

.github/workflows/staging-deploy.yml

Update the Staging deploy workflow to include the task definition name.  This causes the ECS service to correctly use the latest ACTIVE task definition.
Also hides the command output to prevent accidental disclosure of information.
- https://github.com/cds-snc/platform-forms-client/issues/3946

fix: deploy latest ECS task definition

---

.github/workflows/staging-deploy.yml

Update the Staging deployment workflow to wait until the `forms-api` service is stable.  This will cause the workflow to fail if the service cannot be deployed and run as expected.
- https://github.com/cds-snc/platform-forms-client/issues/3946

feat: wait for service deployment stability

---

.env.example
package.json
pnpm-lock.yaml
src/config.ts
src/lib/idp/introspectToken.ts
src/lib/idp/introspectionCache.ts
src/lib/redisConnector.ts
src/middleware/authentication/middleware.ts
test/lib/idp/introspectionCache.test.ts
test/lib/redisConnector.test.ts
test/middleware/authentication/middleware.test.ts
vitest-setup.ts

Add a Redis connector and logic to cache the access token's introspection result for a short period.  This is being done to improve performance and reduce strain on the IdP.
The Redis connector uses the singleton promise pattern so only one client connection will be shared for requests.
Additionally, the cache expiry time is being kept short and the introspection token response expiry will take
precedence.  This prevents an access token from being kept "valid" past its intended expiration time.
1. Generate an access key and token for a form.
2. Perform a request to one of the API's authenticated paths for the form.
3. Expect that on first request, no cached introspection token will be found.
4. Expect that on subsequent requests, a cached token is retrieved and that this cache expires …

feat: add token authentication cache

---

src/lib/vault/dataStructures/exceptions.ts
src/lib/vault/reportProblemWithFormSubmission.ts
src/routes/forms/submission/submissionName/problem/router.ts
test/routes/forms/submission/submissionName/problem/router.test.ts

- Handles submissions already reported as problematic when hitting the `/problem` API path with the same submission multiple times

feat: handle submission already reported as problematic when using /problem API path

---

src/lib/connectors/databaseConnector.ts
src/lib/connectors/redisConnector.ts

Testing over the weekend I was able to find a pattern to reliably create Class instances when dealing with async dependencies.
Redis Connector:
- Add an additional property that holds the `connect()` promise and ensure all subsequent callers await the same promise before returning the initialized instance.
Database Connector:
- Invert the condition and calls to satisfy biome.

refactor: Connector classes with async dependencies

---

src/lib/connectors/redisConnector.ts
src/lib/vault/encryptFormSubmission.ts
src/routes/forms/formId/submission/submissionName/router.ts
src/server.ts

- Modifies the `encryptedResponses` property type from Buffer to string (base64 encoded)

refactor: return encrypted responses field as base64 string instead of Buffer

---

src/lib/vault/encryptFormSubmission.ts
utils/responseRetriever/main.ts

- Modifies size of iv/nonce value from 16 to 12 bytes to follow recommendation. Even though Javascript would still be able to handle it, .NET would just throw an exception because a 12 bytes value is expected.
- Modifies the Optimal Asymmetric Encryption Padding from SHA-1 to SHA-256. As @patheard recently said, this will improve the strength of our encryption.

feat: update to form submission crypto configuration

---

.gitignore
.vscode/settings.json
examples/.NET/AccessTokenGenerator.cs
examples/.NET/DataStructures.cs
examples/.NET/FormSubmissionDecrypter.cs
examples/.NET/GCFormsApiClient.cs
examples/.NET/Program.cs
examples/.NET/README.md
examples/.NET/dotnet.csproj

- Adds API client example in .NET
- Follow directions in README.md file located in the .NET example folder

feat: add API client example in .NET

---

examples/nodejs/formIntegrityVerification.ts
examples/nodejs/index.ts
examples/nodejs/types.d.ts
src/lib/vault/dataStructures/formSubmission.ts
src/lib/vault/getFormSubmission.ts
utils/responseRetriever/main.ts

Adds integrity check to utility script and NodeJS example.
API server now returns FormSubmissionChecksum as part of response download.
Out of scope for now is to update the .Net example.  It will be tackled in a later PR after the API Server is returning the new checksum value.

feature: Add integrity check and update Node example

---

.github/workflows/prod-docker-build-push.yml

Update the prod Docker build/push workflow so that the newly generated SBOM can be written to the repo's security events.
- Closes https://github.com/cds-snc/platform-forms-client/issues/4289

fix: allow SBOM to be written to repo security events

---

examples/nodejs/package-lock.json
examples/nodejs/package.json
utils/responseRetriever/package.json
utils/responseRetriever/pnpm-lock.yaml

- Follow-up PR for https://github.com/cds-snc/forms-api/pull/82 to bump packages in modules outside of API code.

chore: bump packages for modules outside of API code to latest version

---

.github/workflows/docker-vulnerability-scan.yml
.github/workflows/prod-docker-build-push.yml
.github/workflows/staging-docker-build-push.yml

Update the Docker scan actions to use a self-hosted Trivy vulnerability database. This is being done to address the rate limiting of the publicly hosted database.
- https://github.com/cds-snc/platform-core-services/issues/597

fix: use CDS Trivy vulnerability database

---

examples/bash/.env.staging
examples/bash/README.md
examples/bash/confirm_form_submission.sh
examples/bash/get_form_submission.sh
examples/bash/get_form_template.sh
examples/bash/get_new_form_submissions.sh
examples/bash/report_problem_with_form_submission.sh
examples/dotnet/DataStructures.cs
examples/dotnet/GCFormsApiClient.cs
examples/dotnet/Program.cs
examples/nodejs/gcFormsApiClient.ts
examples/nodejs/index.ts
examples/nodejs/types.d.ts
examples/python/data_structures.py
examples/python/gc_forms_api_client.py
examples/python/main.py

- API integration examples use `formId` from API private key file instead of asking for it

feat: API integration examples use formId from API private key file

---

src/middleware/authentication.ts
test/middleware/authentication.test.ts

- Found a bug when looking at some of our API logs. Authentication middleware tries to send a JSON payload but the HTTP response was already completed.

fix: authentication middleware tries to send JSON message as part of the response after the HTTP response has completed

---

src/lib/vault/confirmFormSubmission.ts
src/lib/vault/getFormSubmission.ts
src/lib/vault/reportProblemWithFormSubmission.ts
test/lib/vault/confirmFormSubmission.test.ts
test/lib/vault/getFormSubmission.test.ts
test/lib/vault/reportProblemWithFormSubmission.test.ts
test/mocks/dynamodb.ts

Part 7 of https://github.com/cds-snc/platform-forms-client/issues/4287
- Replaces any reference to the old `Status` with new `Status#CreatedAt` attribute when requesting Vault items.

refactor: replace use of Status with new Status#CreatedAt attribute when requesting Vault items

---

examples/dotnet/README.md
examples/dotnet/dotnet.csproj
examples/nodejs/README.md
examples/nodejs/package-lock.json
examples/nodejs/package.json
examples/python/main.py
package.json
pnpm-lock.yaml

- Updates all API integration examples to use latest version for frameworks and package dependencies
- Uses latest version of `tsc-alias` for the API build now that it got fixed (https://github.com/justkey007/tsc-alias/commit/3e55ed9a8fc14a9a59ec490f2a0ecedc8dd509ea)

chore: update API integration examples to use latest version of frameworks/package dependencies

---

src/operations/checkServiceHealth.ts

- Catches error in check service health API operation. This would have been helpful when debugging the missing DynamoDB Scan permission).

chore: catch error in check service health operation (it can help debug issues like a missing permission on DynamoDB)

---

.github/workflows/release-generator.yml

Update the release please workflow to use a dedicated GitHub app for releases. This will allow us to scale back the use of the SRE read/write GitHub app.
- https://github.com/cds-snc/platform-core-services/issues/707

chore:  switch to CDS Release Bot

---

src/operations/checkServiceHealth.ts
test/operations/checkServiceHealth.test.ts
vitest-setup.ts

- Reverts `/status` endpoint changes to make it simple and just return HTTP 200 with JSON { "status": "running" }

chore: revert complex status endpoint logic

---

examples/bash/README.md
examples/bash/confirm_form_submission.sh
examples/bash/decrypt_form_submission.sh
examples/bash/get_form_submission.sh
examples/bash/get_form_template.sh
examples/bash/get_new_form_submissions.sh
examples/bash/retrieve_save_confirm_form_submissions.sh
examples/bash/validate_form_submission.sh
examples/dotnet/DataStructures.cs
examples/dotnet/GCFormsApiClient.cs
examples/dotnet/Program.cs
examples/dotnet/dotnet.csproj
examples/nodejs/index.ts
examples/python/data_structures.py
examples/python/main.py

- Adds support for submission attachments in all API integration examples
- Reworks some of the Bash scripts to make them compatible with the new `retrieve_save_confirm_form_submissions.sh` script that shows how to combine every smaller scripts to leverage all API features
List of examples:

chore: add submission attachments support to API examples

---

src/lib/vault/mappers/formSubmission.mapper.ts
src/lib/vault/types/formSubmission.types.ts
src/operations/retrieveSubmission.v1.ts
test/lib/vault/mappers/formSubmission.mapper.test.ts
test/operations/retrieveSubmission.v1.test.ts

Adds attachment ID to the object so that it is easier to identify to which form response it corresponds.

feature: Add ID to attachment object
